### ISSUE TITLE
pre-process codes available?

### ISSUE THREAD

**Issue by q671383789** [hust-linyi/MedISeg#3]
Hey, I want to know is the codes available u guys mentioned in Sec3.2 OverSam part

**Comment by hust-linyi** [comment]
> Hey, I want to know is the codes available u guys mentioned in Sec3.2 OverSam part

Yes, you may find the key code here, https://github.com/hust-linyi/MedISeg/blob/cdfc4499c0f565ccd2c24ec64e86cfb14180350e/3DUNet/NetworkTrainer/dataloaders/dataload.py#L71
