### ISSUE TITLE
Dataset Path in 2D network trainer

### ISSUE THREAD

**Issue by OmerMansoor** [hust-linyi/MedISeg#4]
I am facing an error regarding the dataset path while running the 2DUNET network trainer. I tried my best but cannot find where you provided the code to place path of the data set in dataload.py.  

Can you please tell me where exactly you have provided the path of the dataset in the 2dUnet data loader?

I am a newbie to python and am having a little bit of difficulty. If you can please tell it would be of great help.

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\HP/Data/ISIC-2018\\NumpyData\\img.npy'
This is the exact error shown

**Comment by hust-linyi** [comment]
> I am facing an error regarding the dataset path while running the 2DUNET network trainer. I tried my best but cannot find where you provided the code to place path of the data set in dataload.py.
> 
> Can you please tell me where exactly you have provided the path of the dataset in the 2dUnet data loader?
> 
> I am a newbie to python and am having a little bit of difficulty. If you can please tell it would be of great help.
> 
> FileNotFoundError: [Errno 2] No such file or directory: 'C:\Users\HP/Data/ISIC-2018\NumpyData\img.npy' This is the exact error shown

Here it is, thanks.
https://github.com/hust-linyi/MedISeg/blob/68013a6233b05e96e6d4bfe47ccb6406d2db1212/2DUNet/NetworkTrainer/options.py#L54
