### ISSUE TITLE
How to pre-process lits2017 dataset?

### ISSUE THREAD

**Issue by Luffy03** [hust-linyi/MedISeg#5]
Hi, I download the lits2017 dataset like this. But I cannot run the training code directly.
Can you give me more instructions about how to preprocess the dataset? Data name and path?
![image](https://user-images.githubusercontent.com/52514670/218959814-9b4f7e27-4850-4388-a23c-46c3e822bf08.png)

**Comment by ianyilin** [comment]
Hi, 

You may first preprocess the data with the following code:
https://github.com/hust-linyi/MedISeg/blob/main/3DUNet/pre_processing/data_prepare.py

Thanks,
Yi

**Comment by Luffy03** [comment]
Thanks!
