### ISSUE TITLE
How to train lits dataset?

### ISSUE THREAD

**Issue by Wanyidon** [hust-linyi/MedISeg#6]
I have finished preprocessing the LITS data, but it runs particularly slow in the early stages of training. I'm wondering what the problem is as it's only running at one-tenth the speed of the KITS9 dataset？ Thanks!

**Comment by ianyilin** [comment]
> 

Hi, Yidon. You may modify the get_imglist() function here: https://github.com/hust-linyi/MedISeg/blob/68013a6233b05e96e6d4bfe47ccb6406d2db1212/3DUNet/NetworkTrainer/dataloaders/dataload.py#L8

For example, you can set the variables "start" and "end" in "image_list[start:end]", by which you can use a small portion of the entire dataset.

**Comment by Wanyidon** [comment]
Thank you, I will give it a try.

**Comment by Wanyidon** [comment]
Sorry, i also want to know where the pre-processing code for 2D? I couldn't find it in the folder.Thanks!

**Comment by dddraxxx** [comment]
Same question. Is there any preprocessing code?

**Comment by ianyilin** [comment]
For 2D datasets, I just concatenate all the images as a single numpy file.
The pre-process (e.g., resize, intensity normalization) can be found here:
https://github.com/hust-linyi/MedISeg/blob/68013a6233b05e96e6d4bfe47ccb6406d2db1212/2DUNet/NetworkTrainer/dataloaders/get_transform.py#L8
