### ISSUE TITLE
NetworkTrainer/train.py set_GPU_device

### ISSUE THREAD

**Issue by xiaofang007** [hust-linyi/MedISeg#9]
It seems that after running set_GPU_device the process will use all the gpus that the server has instead of the gpu ids I choose (In other words, os.environ['cuda_visible_devices'] does not have any effect). Maybe it is because when train.py import NetworkTrainer from network_trainer, it imports torch simultaneously. Thanks.

**Comment by dongzhang89** [comment]
@xiaofang007 Thanks Xiaofang for the report.

**Comment by hust-linyi** [comment]
Fixed, thanks.
